# Generated by Django 5.2.1 on 2025-05-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل شرکت')),
                ('password', models.CharField(max_length=128, verbose_name='رمز عبور')),
                ('responsible_person', models.CharField(max_length=255, verbose_name='نام مسئول')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='موبایل')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='لوگو')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب سایت')),
                ('Province', models.TextField(max_length=100, verbose_name='استان')),
                ('city', models.TextField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
                'db_table': 'Company',
            },
        ),
    ]
