# Generated by Django 5.2.1 on 2025-05-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='apps/Account/company_logos/', verbose_name='لوگو'),
        ),
    ]
