# Generated by Django 5.2.1 on 2025-05-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cis_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciscontrol',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='ciscontrol',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='ciscontrol',
            name='title',
            field=models.CharField(max_length=256, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='ciscontrol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
